# Generated by Django 6.0.2 on 2026-02-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('product_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='products.productstore')),
            ],
            options={
                'db_table': 'price_snapshots',
                'indexes': [models.Index(fields=['product_store', 'created_at'], name='price_snaps_product_99a208_idx')],
            },
        ),
    ]
