# Generated by Django 6.0.2 on 2026-02-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date', models.DateField(db_index=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='currencies.currency')),
            ],
            options={
                'db_table': 'exchange_rates',
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='unique_currency_date')],
            },
        ),
    ]
