# Generated by Django 6.0.2 on 2026-02-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('dummyjson', 'Dummyjson'), ('fakestore', 'Fakestore')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stores', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stores', to='products.store')),
            ],
            options={
                'db_table': 'product_stores',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(related_name='products', through='products.ProductStore', to='products.store'),
        ),
        migrations.AddIndex(
            model_name='productstore',
            index=models.Index(fields=['store', 'external_id'], name='product_sto_store_i_8f461e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productstore',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='uniq_product_store'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
    ]
