# Generated by Django 6.0.2 on 2026-02-24 18:30

from django.db import migrations


def add_default_stores(apps, schema_editor):
    Store = apps.get_model("products", "Store")
    Store.objects.get_or_create(
        slug="dummyjson", defaults={"name": "Dummyjson"}
    )
    Store.objects.get_or_create(
        slug="fakestore", defaults={"name": "Fakestore"}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_stores, migrations.RunPython.noop),
    ]
