# Generated by Django 6.0.2 on 2026-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_default_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='external_id',
            field=models.BigIntegerField(),
        ),
    ]
